// <auto-generated />
using System;
using ElectricityMeterportal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectricityMeterportal.Migrations
{
    [DbContext(typeof(ElectricityMeterDbContext))]
    partial class ElectricityMeterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectricityMeterportal.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BillID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("BillDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("Consumption")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("CurrentReading")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("MeterId")
                        .HasColumnType("int")
                        .HasColumnName("MeterID");

                    b.Property<decimal>("PreviousReading")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("BillId")
                        .HasName("PK__Bills__11F2FC4A0CFA206C");

                    b.HasIndex("MeterId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("ElectricityMeterportal.Models.ElectricityRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeterType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.HasKey("ID");

                    b.ToTable("ElectricityRequests", (string)null);
                });

            modelBuilder.Entity("ElectricityMeterportal.Models.Meter", b =>
                {
                    b.Property<int>("MeterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MeterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeterId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MeterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("MeterId")
                        .HasName("PK__Meters__59223B8C7431AE87");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("Meters");
                });

            modelBuilder.Entity("ElectricityMeterportal.Models.MeterReading", b =>
                {
                    b.Property<int>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReadingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReadingId"));

                    b.Property<int>("MeterId")
                        .HasColumnType("int")
                        .HasColumnName("MeterID");

                    b.Property<DateTime?>("ReadingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("ReadingValue")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ReadingId")
                        .HasName("PK__MeterRea__C80F9C6E5BE448B0");

                    b.HasIndex("MeterId");

                    b.ToTable("MeterReadings");
                });

            modelBuilder.Entity("ElectricityMeterportal.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int")
                        .HasColumnName("BillID");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A58A06DB9AE");

                    b.HasIndex("BillId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ElectricityMeterportal.Models.RequestDocument", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElectricityRequestID")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ElectricityRequestID");

                    b.ToTable("RequestDocuments");
                });

            modelBuilder.Entity("ElectricityMeterportal.Models.Bill", b =>
                {
                    b.HasOne("ElectricityMeterportal.Models.Meter", "Meter")
                        .WithMany("Bills")
                        .HasForeignKey("MeterId")
                        .IsRequired()
                        .HasConstraintName("FK__Bills__BillDate__59063A47");

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("ElectricityMeterportal.Models.Meter", b =>
                {
                    b.HasOne("ElectricityMeterportal.Models.ElectricityRequest", "Request")
                        .WithOne("Meter")
                        .HasForeignKey("ElectricityMeterportal.Models.Meter", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ElectricityMeterportal.Models.MeterReading", b =>
                {
                    b.HasOne("ElectricityMeterportal.Models.Meter", "Meter")
                        .WithMany("MeterReadings")
                        .HasForeignKey("MeterId")
                        .IsRequired()
                        .HasConstraintName("FK__MeterRead__Readi__4F7CD00D");

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("ElectricityMeterportal.Models.Payment", b =>
                {
                    b.HasOne("ElectricityMeterportal.Models.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__BillID__5CD6CB2B");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("ElectricityMeterportal.Models.RequestDocument", b =>
                {
                    b.HasOne("ElectricityMeterportal.Models.ElectricityRequest", "ElectricityRequest")
                        .WithMany("Documents")
                        .HasForeignKey("ElectricityRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElectricityRequest");
                });

            modelBuilder.Entity("ElectricityMeterportal.Models.Bill", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ElectricityMeterportal.Models.ElectricityRequest", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("ElectricityMeterportal.Models.Meter", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("MeterReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
